---
# vim: set ft=ansible:

- name: Create secrets directory
  file:
    path: "{{item}}"
    state: directory
    mode: 0o700
  with_items:
    - "{{secrets_dir}}"
    - "{{secrets_docker_tls}}"
  delegate_to: 127.0.0.1

