language: python
python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install -r requirements/doc.txt

script: "python setup.py build_sphinx && bash doc/scripts/publish-docs.sh"

notifications:
  email: false

branches:
  only:
  - master
