---
# vim: set ft=ansible:

- meta: flush_handlers

- stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: restart server
  become: yes
  become_user: root
  shell: sleep 2 && shutdown -r now "Ansible restarting after apt upgrade"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists == True

- name: waiting for server to come back
  become: no
  wait_for:
    host: "{{reboot_ip}}"
    port: 22
    state: started
    delay: 30
    timeout: 300
  delegate_to: 127.0.0.1
  when: reboot_required.stat.exists == True

