---
# vim: set ft=ansible:

- name: reload supervisor
  become: yes
  become_user: root
  command: supervisorctl reload

- name: restart ats.gateway
  become: yes
  become_user: root
  command: supervisorctl restart ats-gateway

