---
# vim: set ft=ansible:

- name: upload docker images
  # become + synchronize is bugged if non root
  # become + copy to workspace is a memory hog
  # (see https://github.com/ansible/ansible/issues/11702)
  # no become + copy is still a memory hog
  become: no
  synchronize:
    src: "{{docker_images_path}}"
    dest: /home/ubuntu/

- name: set image permissions
  # make image archive readable by deploy_user
  become: no
  file:
    path: /home/ubuntu/docker-images.tar
    state: touch
    mode: u=rw,g=r,o=r

- name: load docker images
  command: docker load -i /home/ubuntu/docker-images.tar

