---
# vim: set ft=ansible
#

- name: Create docker dir
  file:
    path: "{{docker_dir}}"
    state: directory
    mode: 0o700
  become: yes
  become_user: root

- name: Copy server certificate
  copy:
    src: "{{secrets_docker_tls}}/server-cert.pem"
    dest: "{{docker_dir}}/server-cert.pem"
    mode: 0o400
  become: yes
  become_user: root

- name: Copy client key
  copy:
    src: "{{secrets_docker_tls}}/server-key.pem"
    dest: "{{docker_dir}}/server-key.pem"
    mode: 0o400
  become: yes
  become_user: root

- name: Copy CA cert
  copy:
    src: "{{secrets_docker_tls}}/ca.pem"
    dest: "{{docker_dir}}/ca.pem"
    mode: 0o400
  become: yes
  become_user: root
