---
# vim: set ft=ansible:

- name: Deploy an ATS server (AMQP + services)

  hosts: ats
  force_handlers: True

  vars:
    - ansible_ssh_pipelining: yes
    - deploy_user: "{{ats_user}}"
    - workspace: /home/{{deploy_user}}/aic
    - secrets_docker_tls: "{{secrets_dir}}/docker/tls"

  pre_tasks:
    - include_vars: "{{local_etc}}/config-ats.yml"
    - include_vars: ats-vars.yml

  roles:
    #
    # Common roles, user and mail setup
    #

    - role: common/exit-if-apt-running
    - role: common/exit-if-local
    - role: common/create-secrets
    - role: common/hosts
    - role: ats/hosts
    - role: common/mail
      root_alias: "{{admin_email}}"
    -
      role: common/create-user
      username: "{{deploy_user}}"

    #
    # Workspace
    #

    -
      role: common/git
      become: yes
      become_user: "{{deploy_user}}"
    -
      role: ats/workspace
      become: yes
      become_user: "{{deploy_user}}"

    #
    # AMQP, DBMS
    #

    -
      role: ats/rabbitmq
      become: yes
      become_user: root
    - role: ats/postgres

    #
    # AiC deployment
    #

    -
      role: ats/service-gateway
      become: yes
      become_user: "{{deploy_user}}"
    -
      role: ats/service-auth
      become: yes
      become_user: "{{deploy_user}}"
    -
      role: ats/service-kyaraben
      become: yes
      become_user: "{{deploy_user}}"
    -
      role: ats/service-senza
      become: yes
      become_user: "{{deploy_user}}"
    -
      role: ats/service-frontend-dev
      become: yes
      become_user: "{{deploy_user}}"
      when: git.ats.ats_frontend.develop
    -
      role: ats/service-frontend
      become: yes
      become_user: "{{deploy_user}}"
      when: not git.ats.ats_frontend.develop

    #
    # Docker, docker-compose, etc.
    #

    - role: common/docker-create-tls-keys
      delegate_to: 127.0.0.1
    -
      role: ats/docker-key-client
      become: yes
      become_user: "{{deploy_user}}"
    -
      role: common/docker-engine
      docker_hosts:
        - fd://
        - unix:///var/run/docker.sock
      docker_conf_suffix: ""
    - role: common/docker-compose
    - role: ats/docker-bashrc-config
#    - role: ats/docker-registry

    #
    # Reboot if the kernel has been upgraded, notify the admin
    #

    - role: common/reboot-if-required
      reboot_ip: "{{ hostvars['ats']['ip_floating'] }}"
    - role: common/mail-notification

