---
# vim: set ft=ansible:

- name: Upload player images to an SDL server (docker host)

  hosts: sdl
  force_handlers: True

  vars:
    - ansible_ssh_pipelining: yes
    - deploy_user: "{{sdl_user}}"
    - workspace: /home/{{deploy_user}}/aic

  roles:
    - role: common/exit-if-local
    -
      role: player/install-playerimage
      become: yes
      become_user: "{{deploy_user}}"

